# Generated by Django 4.2.8 on 2024-04-07 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=5)),
                ('availability', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.ForeignKey(help_text='current location of the property.', on_delete=django.db.models.deletion.CASCADE, to='core.location')),
                ('owner', models.ForeignKey(help_text='user that posted the listing.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property_type', models.ForeignKey(help_text='type of apartment being rented', on_delete=django.db.models.deletion.CASCADE, to='core.propertytype')),
                ('unit', models.ForeignKey(help_text='days, weeks, months during which property is unavailable.', on_delete=django.db.models.deletion.CASCADE, to='core.unit')),
            ],
        ),
    ]
