# Generated by Django 4.2.8 on 2024-04-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='availability',
        ),
        migrations.AddField(
            model_name='property',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
